### ISSUE TITLE
Expresividad en los predicados

### ISSUE THREAD

**Issue by josibuttazzoni** [tomi-iglesias/democracia#1]
Traten siempre que se entienda un poco mas que es lo que realmente relaciona cada predicado. Por ejemplo, para la edad de los candidatos, podría ser `edad(Años, Candidato)`, la de la cantidad de habitantes `habitantes(Provincia, Cantidad)`

**Comment by tomi-iglesias** [comment]
Ok josi, entendido, Gracias
