### ISSUE TITLE
Delegar en nuevos predicados

### ISSUE THREAD

**Issue by josibuttazzoni** [tomi-iglesias/democracia#2]
En `esPicante` podrian haber hecho otro predicado que fuera, por ejemplo, `sePresentanPorLoMenosDosPartidos(Provincia)` y hubiera quedado un poco mas prolijo todo. Y, también, `esProvinciaGrande` podría dar indicio de que es lo que implica. Podría llamarse `masDeUnMillonDeHabitantes`, o algo por el estilo
```prolog
esPicante(Provincia):- 
	masDeUnMillonDeHabitantes(Provincia), 
	sePresentanPorLoMenosDosPartidos(Provincia).
```

**Comment by josibuttazzoni** [comment]
Lo mismo en `esElMasJovenDeSuPartido`, podrian haber hecho un predicado que fuera `esMenor(UnCandidato, OtroCandidato) `y usarlo en el consecuente del forall.

**Comment by tomi-iglesias** [comment]
Corregido!
